[2025-03-03T17:16:39.758+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_transformation_task manual__2025-03-03T17:15:40.663621+00:00 [queued]>
[2025-03-03T17:16:39.778+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_transformation_task manual__2025-03-03T17:15:40.663621+00:00 [queued]>
[2025-03-03T17:16:39.778+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-03T17:16:39.818+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_transformation_task> on 2025-03-03 17:15:40.663621+00:00
[2025-03-03T17:16:39.828+0000] {standard_task_runner.py:57} INFO - Started process 8292 to run task
[2025-03-03T17:16:39.835+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_transformation_task', 'manual__2025-03-03T17:15:40.663621+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmp4inxmqra']
[2025-03-03T17:16:39.840+0000] {standard_task_runner.py:85} INFO - Job 156: Subtask data_transformation_task
[2025-03-03T17:16:39.891+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T17:16:39.984+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_transformation_task manual__2025-03-03T17:15:40.663621+00:00 [running]> on host 157237bff8f7
[2025-03-03T17:16:40.175+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_transformation_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T17:15:40.663621+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T17:15:40.663621+00:00'
[2025-03-03T17:16:40.177+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-03T17:16:40.178+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t\t\tcd /opt/*** &&                        dvc pull /opt/***/data/cleaned\n                        python /opt/***/executables/data_transformation.py &&                         dvc add /opt/***/data/transformed &&                         git add /opt/***/data/transformed.dvc && \t\t\tgit add logs &&    \t\t\tgit status &&                         git commit -m "Updated transformed data version" -a &&                         dvc push && git push\n                    ']
[2025-03-03T17:16:40.194+0000] {subprocess.py:86} INFO - Output:
[2025-03-03T17:16:43.434+0000] {subprocess.py:93} INFO - WARNING: failed to collect 'workspace', skipping
[2025-03-03T17:16:43.434+0000] {subprocess.py:93} INFO - ERROR: failed to pull data from the cloud - '/opt/***/data/cleaned' does not exist as an output or a stage name in 'dvc.yaml': 'dvc.yaml' does not exist
[2025-03-03T17:16:46.224+0000] {subprocess.py:93} INFO - 2025-03-03 17:16:46,224 : INFO : Starting data transformation for csv.
[2025-03-03T17:16:46.269+0000] {subprocess.py:93} INFO - 2025-03-03 17:16:46,268 : INFO : Scaling 'Tenure', 'Balance', 'EstimatedSalary'.
[2025-03-03T17:16:46.280+0000] {subprocess.py:93} INFO - 2025-03-03 17:16:46,279 : INFO : Saving data to S3.
[2025-03-03T17:16:49.328+0000] {subprocess.py:93} INFO - 2025-03-03 17:16:49,327 : INFO : Starting data transformation for csv.
[2025-03-03T17:16:49.329+0000] {subprocess.py:93} INFO - 2025-03-03 17:16:49,329 : ERROR : Failed data transformation: [Errno 2] No such file or directory: '/opt/***/data/cleaned/fintech2/03-03-2025/database/database_data.csv'
[2025-03-03T17:16:51.136+0000] {subprocess.py:93} INFO - 
[2025-03-03T17:16:51.137+0000] {subprocess.py:93} INFO - To track the changes with git, run:
[2025-03-03T17:16:51.137+0000] {subprocess.py:93} INFO - 
[2025-03-03T17:16:51.137+0000] {subprocess.py:93} INFO - 	git add data/transformed.dvc
[2025-03-03T17:16:51.137+0000] {subprocess.py:93} INFO - 
[2025-03-03T17:16:51.138+0000] {subprocess.py:93} INFO - To enable auto staging, run:
[2025-03-03T17:16:51.138+0000] {subprocess.py:93} INFO - 
[2025-03-03T17:16:51.138+0000] {subprocess.py:93} INFO - 	dvc config core.autostage true
[2025-03-03T17:16:51.421+0000] {subprocess.py:93} INFO - On branch main
[2025-03-03T17:16:51.422+0000] {subprocess.py:93} INFO - Your branch is up to date with 'origin/main'.
[2025-03-03T17:16:51.422+0000] {subprocess.py:93} INFO - 
[2025-03-03T17:16:51.423+0000] {subprocess.py:93} INFO - Changes to be committed:
[2025-03-03T17:16:51.423+0000] {subprocess.py:93} INFO -   (use "git restore --staged <file>..." to unstage)
[2025-03-03T17:16:51.423+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T17:15:40.663621+00:00/task_id=data_preparation_task/attempt=1.log
[2025-03-03T17:16:51.423+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T17:15:40.663621+00:00/task_id=data_transformation_task/attempt=1.log
[2025-03-03T17:16:51.423+0000] {subprocess.py:93} INFO - 	modified:   logs/data_transformation.log
[2025-03-03T17:16:51.424+0000] {subprocess.py:93} INFO - 
[2025-03-03T17:16:51.424+0000] {subprocess.py:93} INFO - Untracked files:
[2025-03-03T17:16:51.424+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to include in what will be committed)
[2025-03-03T17:16:51.425+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/online_store.db
[2025-03-03T17:16:51.425+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/registry.db
[2025-03-03T17:16:51.425+0000] {subprocess.py:93} INFO - 	models/
[2025-03-03T17:16:51.425+0000] {subprocess.py:93} INFO - 	online.db
[2025-03-03T17:16:51.425+0000] {subprocess.py:93} INFO - 
[2025-03-03T17:16:51.442+0000] {subprocess.py:93} INFO - [main 2632b31] Updated transformed data version
[2025-03-03T17:16:51.443+0000] {subprocess.py:93} INFO -  3 files changed, 161 insertions(+)
[2025-03-03T17:16:51.443+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T17:15:40.663621+00:00/task_id=data_preparation_task/attempt=1.log
[2025-03-03T17:16:51.443+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T17:15:40.663621+00:00/task_id=data_transformation_task/attempt=1.log
[2025-03-03T17:16:56.546+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-03T17:16:58.326+0000] {subprocess.py:93} INFO - To https://github.com/anniemathew-trial/customer_churn_pipeline.git
[2025-03-03T17:16:58.327+0000] {subprocess.py:93} INFO -    8b91f07..2632b31  main -> main
[2025-03-03T17:16:58.336+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-03T17:16:58.378+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=customer_churn_ml_pipeline, task_id=data_transformation_task, execution_date=20250303T171540, start_date=20250303T171639, end_date=20250303T171658
[2025-03-03T17:16:58.414+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-03T17:16:58.454+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
