[2025-03-01T11:26:34.986+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_ingestion_task manual__2025-03-01T11:26:24.198717+00:00 [queued]>
[2025-03-01T11:26:35.006+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_ingestion_task manual__2025-03-01T11:26:24.198717+00:00 [queued]>
[2025-03-01T11:26:35.007+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-01T11:26:35.043+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_ingestion_task> on 2025-03-01 11:26:24.198717+00:00
[2025-03-01T11:26:35.052+0000] {standard_task_runner.py:57} INFO - Started process 14165 to run task
[2025-03-01T11:26:35.058+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_ingestion_task', 'manual__2025-03-01T11:26:24.198717+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmplslbb5vl']
[2025-03-01T11:26:35.069+0000] {standard_task_runner.py:85} INFO - Job 130: Subtask data_ingestion_task
[2025-03-01T11:26:35.107+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-01T11:26:35.183+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_ingestion_task manual__2025-03-01T11:26:24.198717+00:00 [running]> on host 7e994a0ed489
[2025-03-01T11:26:35.435+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_ingestion_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T11:26:24.198717+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-01T11:26:24.198717+00:00'
[2025-03-01T11:26:35.437+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-01T11:26:35.439+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/executables/data_ingestion.py && \t\t\tcd /opt/*** && \t\t\tgit rm -r --cached \'data/raw\'\n\t\t\tgit commit -m "stop tracking data/raw"\n                        dvc add /opt/***/data/raw &&                         git add /opt/***/data/raw.dvc && \t\t\tgit add logs &&                        git commit -m "Updated raw data version" -a &&                         dvc push && git push\n                    ']
[2025-03-01T11:26:35.457+0000] {subprocess.py:86} INFO - Output:
[2025-03-01T11:26:36.651+0000] {subprocess.py:93} INFO - 2025-03-01 11:26:36,651 : INFO : Reading data from CSV file customer_data.csv
[2025-03-01T11:26:36.755+0000] {subprocess.py:93} INFO - 2025-03-01 11:26:36,755 : INFO : Data from CSV customer_data.csv ingested successfully!
[2025-03-01T11:26:36.756+0000] {subprocess.py:93} INFO - 2025-03-01 11:26:36,755 : INFO : Connecting to Database
[2025-03-01T11:26:36.780+0000] {subprocess.py:93} INFO - 2025-03-01 11:26:36,780 : INFO : Connecting to Database Successfull
[2025-03-01T11:26:36.781+0000] {subprocess.py:93} INFO - 2025-03-01 11:26:36,780 : INFO : Reading data from database.
[2025-03-01T11:26:37.260+0000] {subprocess.py:93} INFO - /opt/***/executables/data_ingestion.py:46: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-03-01T11:26:37.261+0000] {subprocess.py:93} INFO -   data = pd.read_sql(query, connection)
[2025-03-01T11:26:37.261+0000] {subprocess.py:93} INFO - 2025-03-01 11:26:37,260 : INFO : Data from Database ingested successfully!
[2025-03-01T11:26:37.402+0000] {subprocess.py:93} INFO - fatal: pathspec 'data/raw' did not match any files
[2025-03-01T11:26:37.418+0000] {subprocess.py:93} INFO - On branch main
[2025-03-01T11:26:37.419+0000] {subprocess.py:93} INFO - Your branch is up to date with 'origin/main'.
[2025-03-01T11:26:37.419+0000] {subprocess.py:93} INFO - 
[2025-03-01T11:26:37.420+0000] {subprocess.py:93} INFO - Last command done (1 command done):
[2025-03-01T11:26:37.420+0000] {subprocess.py:93} INFO -    pick 3c82e37 Initial Commit
[2025-03-01T11:26:37.421+0000] {subprocess.py:93} INFO - No commands remaining.
[2025-03-01T11:26:37.421+0000] {subprocess.py:93} INFO - You are currently editing a commit while rebasing branch 'master' on 'f6df714'.
[2025-03-01T11:26:37.422+0000] {subprocess.py:93} INFO -   (use "git commit --amend" to amend the current commit)
[2025-03-01T11:26:37.422+0000] {subprocess.py:93} INFO -   (use "git rebase --continue" once you are satisfied with your changes)
[2025-03-01T11:26:37.422+0000] {subprocess.py:93} INFO - 
[2025-03-01T11:26:37.423+0000] {subprocess.py:93} INFO - Changes not staged for commit:
[2025-03-01T11:26:37.423+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to update what will be committed)
[2025-03-01T11:26:37.424+0000] {subprocess.py:93} INFO -   (use "git restore <file>..." to discard changes in working directory)
[2025-03-01T11:26:37.424+0000] {subprocess.py:93} INFO - 	modified:   dags/__pycache__/customer_churn.cpython-38.pyc
[2025-03-01T11:26:37.425+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-01T11:18:49.240636+00:00/task_id=model_training_task/attempt=1.log
[2025-03-01T11:26:37.425+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_processor_manager/dag_processor_manager.log
[2025-03-01T11:26:37.425+0000] {subprocess.py:93} INFO - 	modified:   logs/data_ingestion.log
[2025-03-01T11:26:37.426+0000] {subprocess.py:93} INFO - 	modified:   logs/scheduler/2025-03-01/customer_churn.py.log
[2025-03-01T11:26:37.426+0000] {subprocess.py:93} INFO - 
[2025-03-01T11:26:37.426+0000] {subprocess.py:93} INFO - Untracked files:
[2025-03-01T11:26:37.426+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to include in what will be committed)
[2025-03-01T11:26:37.427+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/
[2025-03-01T11:26:37.427+0000] {subprocess.py:93} INFO - 	logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-01T11:26:24.198717+00:00/
[2025-03-01T11:26:37.427+0000] {subprocess.py:93} INFO - 	models/
[2025-03-01T11:26:37.428+0000] {subprocess.py:93} INFO - 
[2025-03-01T11:26:37.428+0000] {subprocess.py:93} INFO - no changes added to commit (use "git add" and/or "git commit -a")
[2025-03-01T11:26:39.301+0000] {subprocess.py:93} INFO - 
[2025-03-01T11:26:39.302+0000] {subprocess.py:93} INFO - To track the changes with git, run:
[2025-03-01T11:26:39.302+0000] {subprocess.py:93} INFO - 
[2025-03-01T11:26:39.302+0000] {subprocess.py:93} INFO - 	git add data/raw.dvc
[2025-03-01T11:26:39.302+0000] {subprocess.py:93} INFO - 
[2025-03-01T11:26:39.303+0000] {subprocess.py:93} INFO - To enable auto staging, run:
[2025-03-01T11:26:39.303+0000] {subprocess.py:93} INFO - 
[2025-03-01T11:26:39.303+0000] {subprocess.py:93} INFO - 	dvc config core.autostage true
[2025-03-01T11:26:39.647+0000] {subprocess.py:93} INFO - [main 080359a] Updated raw data version
[2025-03-01T11:26:39.648+0000] {subprocess.py:93} INFO -  7 files changed, 287 insertions(+)
[2025-03-01T11:26:39.648+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-01T11:26:24.198717+00:00/task_id=data_ingestion_task/attempt=1.log
[2025-03-01T11:26:39.649+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-01T11:26:24.198717+00:00/task_id=pull_latest_codes/attempt=1.log
[2025-03-01T11:26:46.201+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-01T11:26:48.094+0000] {subprocess.py:93} INFO - To https://github.com/anniemathew-trial/customer_churn_pipeline.git
[2025-03-01T11:26:48.095+0000] {subprocess.py:93} INFO -    84af2a8..080359a  main -> main
[2025-03-01T11:26:48.103+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-01T11:26:48.171+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=customer_churn_ml_pipeline, task_id=data_ingestion_task, execution_date=20250301T112624, start_date=20250301T112634, end_date=20250301T112648
[2025-03-01T11:26:48.223+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-01T11:26:48.305+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
