[2025-03-02T08:40:22.021+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.model_training_task manual__2025-03-02T08:40:20.735736+00:00 [queued]>
[2025-03-02T08:40:22.035+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.model_training_task manual__2025-03-02T08:40:20.735736+00:00 [queued]>
[2025-03-02T08:40:22.035+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-02T08:40:22.057+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): model_training_task> on 2025-03-02 08:40:20.735736+00:00
[2025-03-02T08:40:22.061+0000] {standard_task_runner.py:57} INFO - Started process 3805 to run task
[2025-03-02T08:40:22.066+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'model_training_task', 'manual__2025-03-02T08:40:20.735736+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmp_brkcs5r']
[2025-03-02T08:40:22.070+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask model_training_task
[2025-03-02T08:40:22.100+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-02T08:40:22.166+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.model_training_task manual__2025-03-02T08:40:20.735736+00:00 [running]> on host 9113a5746a05
[2025-03-02T08:40:22.316+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='model_training_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T08:40:20.735736+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T08:40:20.735736+00:00'
[2025-03-02T08:40:22.317+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-02T08:40:22.318+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t    \t\tcd /opt/***\n       \t\t\t    python /opt/***/executables/model_training.py && \t      \t\t    git add logs &&\t      \t\t    git add mlruns &&                            git commit -m "Trained model version" -a && \\    \n\t\t\t    git push\n                        ']
[2025-03-02T08:40:22.329+0000] {subprocess.py:86} INFO - Output:
[2025-03-02T08:40:22.543+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-03-02T08:40:22.543+0000] {subprocess.py:93} INFO -   File "/opt/***/executables/model_training.py", line 1, in <module>
[2025-03-02T08:40:22.543+0000] {subprocess.py:93} INFO -     from feast import FeatureStore
[2025-03-02T08:40:22.543+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'feast'
[2025-03-02T08:40:23.633+0000] {subprocess.py:93} INFO - Everything up-to-date
[2025-03-02T08:40:23.638+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-02T08:40:23.684+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=customer_churn_ml_pipeline, task_id=model_training_task, execution_date=20250302T084020, start_date=20250302T084022, end_date=20250302T084023
[2025-03-02T08:40:23.727+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-02T08:40:23.752+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
