[2025-03-02T10:15:36.000+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_preparation_task manual__2025-03-02T10:14:57.596453+00:00 [queued]>
[2025-03-02T10:15:36.014+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_preparation_task manual__2025-03-02T10:14:57.596453+00:00 [queued]>
[2025-03-02T10:15:36.014+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-02T10:15:36.035+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_preparation_task> on 2025-03-02 10:14:57.596453+00:00
[2025-03-02T10:15:36.040+0000] {standard_task_runner.py:57} INFO - Started process 10472 to run task
[2025-03-02T10:15:36.043+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_preparation_task', 'manual__2025-03-02T10:14:57.596453+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmp6r3kmv6c']
[2025-03-02T10:15:36.046+0000] {standard_task_runner.py:85} INFO - Job 143: Subtask data_preparation_task
[2025-03-02T10:15:36.071+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-02T10:15:36.130+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_preparation_task manual__2025-03-02T10:14:57.596453+00:00 [running]> on host 9113a5746a05
[2025-03-02T10:15:36.262+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_preparation_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T10:14:57.596453+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T10:14:57.596453+00:00'
[2025-03-02T10:15:36.263+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-02T10:15:36.264+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t\t\tcd /opt/*** &&\t\t\tpython /opt/***/executables/data_preparation.py &&                         dvc add /opt/***/data/cleaned &&                         git add /opt/***/data/cleaned.dvc && \t\t\tgit add logs && \\   \n\t\t\tgit add visualization &&    \t\t\tgit status &&                         git commit -m "Updated cleaned data version" -a &&                         dvc push && git push\n                    ']
[2025-03-02T10:15:36.275+0000] {subprocess.py:86} INFO - Output:
[2025-03-02T10:15:39.100+0000] {subprocess.py:93} INFO - 2025-03-02 10:15:39,100 : INFO : Starting data preparation for csv.
[2025-03-02T10:15:39.122+0000] {subprocess.py:93} INFO - 2025-03-02 10:15:39,121 : INFO : Handling 'Tenure', 'Balance', 'EstimatedSalary' empty data
[2025-03-02T10:15:39.122+0000] {subprocess.py:93} INFO - 2025-03-02 10:15:39,122 : INFO : Handling 'Age' empty data
[2025-03-02T10:15:39.123+0000] {subprocess.py:93} INFO - 2025-03-02 10:15:39,123 : INFO : Droping 'Surname' as it may lead to profiling, 'RowNumber', 'CustomerId' as it is not required
[2025-03-02T10:15:39.126+0000] {subprocess.py:93} INFO - 2025-03-02 10:15:39,125 : INFO : Making 'Geography', 'Gender', 'HasCrCard', 'IsActiveMember' as categorical
[2025-03-02T10:15:39.134+0000] {subprocess.py:93} INFO - 2025-03-02 10:15:39,133 : INFO : Saving data to S3.
[2025-03-02T10:15:39.191+0000] {subprocess.py:93} INFO - 2025-03-02 10:15:39,191 : ERROR : Error in preparing dataname 'boto3' is not defined
[2025-03-02T10:15:41.259+0000] {subprocess.py:93} INFO - 
[2025-03-02T10:15:41.259+0000] {subprocess.py:93} INFO - To track the changes with git, run:
[2025-03-02T10:15:41.259+0000] {subprocess.py:93} INFO - 
[2025-03-02T10:15:41.259+0000] {subprocess.py:93} INFO - 	git add data/cleaned.dvc
[2025-03-02T10:15:41.259+0000] {subprocess.py:93} INFO - 
[2025-03-02T10:15:41.260+0000] {subprocess.py:93} INFO - To enable auto staging, run:
[2025-03-02T10:15:41.260+0000] {subprocess.py:93} INFO - 
[2025-03-02T10:15:41.260+0000] {subprocess.py:93} INFO - 	dvc config core.autostage true
[2025-03-02T10:15:41.533+0000] {subprocess.py:93} INFO - /bin/bash: line 2:  : command not found
[2025-03-02T10:15:41.556+0000] {subprocess.py:93} INFO - On branch main
[2025-03-02T10:15:41.557+0000] {subprocess.py:93} INFO - Your branch is up to date with 'origin/main'.
[2025-03-02T10:15:41.557+0000] {subprocess.py:93} INFO - 
[2025-03-02T10:15:41.557+0000] {subprocess.py:93} INFO - Changes to be committed:
[2025-03-02T10:15:41.557+0000] {subprocess.py:93} INFO -   (use "git restore --staged <file>..." to unstage)
[2025-03-02T10:15:41.558+0000] {subprocess.py:93} INFO - 	modified:   data/cleaned.dvc
[2025-03-02T10:15:41.558+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-02T10:14:57.596453+00:00/task_id=data_preparation_task/attempt=1.log
[2025-03-02T10:15:41.558+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-02T10:14:57.596453+00:00/task_id=data_validation_task/attempt=1.log
[2025-03-02T10:15:41.558+0000] {subprocess.py:93} INFO - 	modified:   logs/data_preparation.log
[2025-03-02T10:15:41.559+0000] {subprocess.py:93} INFO - 
[2025-03-02T10:15:41.559+0000] {subprocess.py:93} INFO - Changes not staged for commit:
[2025-03-02T10:15:41.559+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to update what will be committed)
[2025-03-02T10:15:41.559+0000] {subprocess.py:93} INFO -   (use "git restore <file>..." to discard changes in working directory)
[2025-03-02T10:15:41.559+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-02T10:14:57.596453+00:00/task_id=data_preparation_task/attempt=1.log
[2025-03-02T10:15:41.560+0000] {subprocess.py:93} INFO - 
