[2025-03-09T12:09:58.383+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_ingestion_task manual__2025-03-09T12:09:46.285124+00:00 [queued]>
[2025-03-09T12:09:58.396+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_ingestion_task manual__2025-03-09T12:09:46.285124+00:00 [queued]>
[2025-03-09T12:09:58.396+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-09T12:09:58.415+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_ingestion_task> on 2025-03-09 12:09:46.285124+00:00
[2025-03-09T12:09:58.420+0000] {standard_task_runner.py:57} INFO - Started process 4867 to run task
[2025-03-09T12:09:58.423+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_ingestion_task', 'manual__2025-03-09T12:09:46.285124+00:00', '--job-id', '340', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmpw709bj_3']
[2025-03-09T12:09:58.426+0000] {standard_task_runner.py:85} INFO - Job 340: Subtask data_ingestion_task
[2025-03-09T12:09:58.450+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-09T12:09:58.499+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_ingestion_task manual__2025-03-09T12:09:46.285124+00:00 [running]> on host 157237bff8f7
[2025-03-09T12:09:58.630+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_ingestion_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T12:09:46.285124+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T12:09:46.285124+00:00'
[2025-03-09T12:09:58.632+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-09T12:09:58.632+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/executables/data_ingestion.py && \t\t\tNOW=$(date \'+%d-%m-%Y\') &&\t\t\tcd /opt/*** && \t\t\tgit add logs &&    \t\t\tgit status &&                         git commit -m "Updated data ingestion" -a &&                         git push\n                    ']
[2025-03-09T12:09:58.641+0000] {subprocess.py:86} INFO - Output:
[2025-03-09T12:09:59.599+0000] {subprocess.py:93} INFO - 2025-03-09 12:09:59,599 : INFO : Reading data from CSV file customer_data.csv
[2025-03-09T12:09:59.684+0000] {subprocess.py:93} INFO - 2025-03-09 12:09:59,684 : INFO : Data from CSV customer_data.csv ingested successfully!
[2025-03-09T12:09:59.685+0000] {subprocess.py:93} INFO - 2025-03-09 12:09:59,684 : INFO : Connecting to Database
[2025-03-09T12:09:59.704+0000] {subprocess.py:93} INFO - 2025-03-09 12:09:59,704 : INFO : Connecting to Database Successfull
[2025-03-09T12:09:59.704+0000] {subprocess.py:93} INFO - 2025-03-09 12:09:59,704 : INFO : Reading data from database.
[2025-03-09T12:10:00.077+0000] {subprocess.py:93} INFO - /opt/***/executables/data_ingestion.py:50: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-03-09T12:10:00.077+0000] {subprocess.py:93} INFO -   data = pd.read_sql(query, connection)
[2025-03-09T12:10:00.077+0000] {subprocess.py:93} INFO - 2025-03-09 12:10:00,076 : INFO : Data from Database ingested successfully!
[2025-03-09T12:10:00.246+0000] {subprocess.py:93} INFO - On branch main
[2025-03-09T12:10:00.246+0000] {subprocess.py:93} INFO - Your branch is up to date with 'origin/main'.
[2025-03-09T12:10:00.246+0000] {subprocess.py:93} INFO - 
[2025-03-09T12:10:00.247+0000] {subprocess.py:93} INFO - Changes to be committed:
[2025-03-09T12:10:00.247+0000] {subprocess.py:93} INFO -   (use "git restore --staged <file>..." to unstage)
[2025-03-09T12:10:00.247+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-09T11:44:36.115678+00:00/task_id=model_training_task/attempt=1.log
[2025-03-09T12:10:00.247+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-09T12:09:46.285124+00:00/task_id=data_ingestion_task/attempt=1.log
[2025-03-09T12:10:00.247+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-09T12:09:46.285124+00:00/task_id=pull_latest_codes/attempt=1.log
[2025-03-09T12:10:00.248+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_processor_manager/dag_processor_manager.log
[2025-03-09T12:10:00.248+0000] {subprocess.py:93} INFO - 	modified:   logs/data_ingestion.log
[2025-03-09T12:10:00.248+0000] {subprocess.py:93} INFO - 	modified:   logs/scheduler/2025-03-09/customer_churn.py.log
[2025-03-09T12:10:00.248+0000] {subprocess.py:93} INFO - 
[2025-03-09T12:10:00.248+0000] {subprocess.py:93} INFO - Untracked files:
[2025-03-09T12:10:00.248+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to include in what will be committed)
[2025-03-09T12:10:00.248+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/online_store.db
[2025-03-09T12:10:00.249+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/registry.db
[2025-03-09T12:10:00.249+0000] {subprocess.py:93} INFO - 	mlartifacts/
[2025-03-09T12:10:00.249+0000] {subprocess.py:93} INFO - 	models/
[2025-03-09T12:10:00.249+0000] {subprocess.py:93} INFO - 	online.db
[2025-03-09T12:10:00.249+0000] {subprocess.py:93} INFO - 
[2025-03-09T12:10:00.312+0000] {subprocess.py:93} INFO - [main 75dee1c] Updated data ingestion
[2025-03-09T12:10:00.313+0000] {subprocess.py:93} INFO -  6 files changed, 827 insertions(+)
[2025-03-09T12:10:00.313+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-09T12:09:46.285124+00:00/task_id=data_ingestion_task/attempt=1.log
[2025-03-09T12:10:00.313+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-09T12:09:46.285124+00:00/task_id=pull_latest_codes/attempt=1.log
[2025-03-09T12:10:01.848+0000] {subprocess.py:93} INFO - To https://github.com/anniemathew-trial/customer_churn_pipeline.git
[2025-03-09T12:10:01.849+0000] {subprocess.py:93} INFO -    ef0081c..75dee1c  main -> main
[2025-03-09T12:10:01.859+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-09T12:10:01.906+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=customer_churn_ml_pipeline, task_id=data_ingestion_task, execution_date=20250309T120946, start_date=20250309T120958, end_date=20250309T121001
[2025-03-09T12:10:01.939+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-09T12:10:01.974+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
