[2025-03-01T16:29:03.039+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_storage_task manual__2025-03-01T16:27:21.347826+00:00 [queued]>
[2025-03-01T16:29:03.064+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_storage_task manual__2025-03-01T16:27:21.347826+00:00 [queued]>
[2025-03-01T16:29:03.065+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-01T16:29:03.102+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_storage_task> on 2025-03-01 16:27:21.347826+00:00
[2025-03-01T16:29:03.113+0000] {standard_task_runner.py:57} INFO - Started process 15657 to run task
[2025-03-01T16:29:03.121+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_storage_task', 'manual__2025-03-01T16:27:21.347826+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmpmgabma1j']
[2025-03-01T16:29:03.127+0000] {standard_task_runner.py:85} INFO - Job 150: Subtask data_storage_task
[2025-03-01T16:29:03.173+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-01T16:29:03.272+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_storage_task manual__2025-03-01T16:27:21.347826+00:00 [running]> on host 7e994a0ed489
[2025-03-01T16:29:03.522+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_storage_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T16:27:21.347826+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-01T16:27:21.347826+00:00'
[2025-03-01T16:29:03.524+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-01T16:29:03.526+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t\t\tcd /opt/***\n                        dvc pull /opt/***/data/transformed\n                        python /opt/***/executables/data_storage.py && \t\t\tgit add logs &&                        git commit -m "Updated stored data version" -a &&                         dvc push && git push\n                    ']
[2025-03-01T16:29:03.548+0000] {subprocess.py:86} INFO - Output:
[2025-03-01T16:29:07.857+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-01T16:29:09.589+0000] {subprocess.py:93} INFO - 2025-03-01 16:29:09,588 : INFO : Connecting to Database
[2025-03-01T16:29:09.618+0000] {subprocess.py:93} INFO - 2025-03-01 16:29:09,618 : INFO : Connecting to Database Successfull
[2025-03-01T16:29:09.619+0000] {subprocess.py:93} INFO - 2025-03-01 16:29:09,618 : INFO : Reading Initial DB Setup Script
[2025-03-01T16:29:09.619+0000] {subprocess.py:93} INFO - 2025-03-01 16:29:09,618 : INFO : Executing script to Database
[2025-03-01T16:29:09.636+0000] {subprocess.py:93} INFO - 2025-03-01 16:29:09,636 : INFO : Executed script successfully !!
[2025-03-01T16:29:09.637+0000] {subprocess.py:93} INFO - 2025-03-01 16:29:09,636 : INFO : Reading insert script template
[2025-03-01T16:29:09.637+0000] {subprocess.py:93} INFO - 2025-03-01 16:29:09,636 : INFO : Inserting data to database
[2025-03-01T16:29:16.616+0000] {subprocess.py:93} INFO - 2025-03-01 16:29:16,616 : INFO : Executed script successfully !!
[2025-03-01T16:29:16.617+0000] {subprocess.py:93} INFO - 2025-03-01 16:29:16,617 : INFO : Connection closed !!
[2025-03-01T16:29:16.739+0000] {subprocess.py:93} INFO - [main 118d356] Updated stored data version
[2025-03-01T16:29:16.739+0000] {subprocess.py:93} INFO -  4 files changed, 49 insertions(+)
[2025-03-01T16:29:16.740+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-01T16:27:21.347826+00:00/task_id=data_storage_task/attempt=1.log
[2025-03-01T16:29:22.024+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-01T16:29:24.005+0000] {subprocess.py:93} INFO - To https://github.com/anniemathew-trial/customer_churn_pipeline.git
[2025-03-01T16:29:24.006+0000] {subprocess.py:93} INFO -    c4b32c7..118d356  main -> main
[2025-03-01T16:29:24.011+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-01T16:29:24.047+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=customer_churn_ml_pipeline, task_id=data_storage_task, execution_date=20250301T162721, start_date=20250301T162903, end_date=20250301T162924
[2025-03-01T16:29:24.111+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-01T16:29:24.143+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
