[2025-03-09T10:58:28.079+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.model_training_task scheduled__2025-03-08T08:00:00+00:00 [queued]>
[2025-03-09T10:58:28.089+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.model_training_task scheduled__2025-03-08T08:00:00+00:00 [queued]>
[2025-03-09T10:58:28.089+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-09T10:58:28.105+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): model_training_task> on 2025-03-08 08:00:00+00:00
[2025-03-09T10:58:28.108+0000] {standard_task_runner.py:57} INFO - Started process 895 to run task
[2025-03-09T10:58:28.111+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'model_training_task', 'scheduled__2025-03-08T08:00:00+00:00', '--job-id', '302', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmpijhb0hqr']
[2025-03-09T10:58:28.113+0000] {standard_task_runner.py:85} INFO - Job 302: Subtask model_training_task
[2025-03-09T10:58:28.132+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-09T10:58:28.175+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.model_training_task scheduled__2025-03-08T08:00:00+00:00 [running]> on host 157237bff8f7
[2025-03-09T10:58:28.277+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='model_training_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-08T08:00:00+00:00'
[2025-03-09T10:58:28.278+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-09T10:58:28.279+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t    \t\tcd /opt/***\n       \t\t\t    python /opt/***/executables/model_training.py && \t      \t\t    git add logs && \t      \t\t    git add mlruns && \t        \t    git status &&                             git commit -m "Trained model version" -a && \\    \n\t\t\t    git push\n                        ']
[2025-03-09T10:58:28.286+0000] {subprocess.py:86} INFO - Output:
[2025-03-09T10:58:35.180+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.8/site-packages/mlflow/gateway/config.py:64: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
[2025-03-09T10:58:35.181+0000] {subprocess.py:93} INFO -   @validator("togetherai_api_key", pre=True)
[2025-03-09T10:58:35.181+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.8/site-packages/mlflow/gateway/config.py:372: PydanticDeprecatedSince20: Pydantic V1 style `@root_validator` validators are deprecated. You should migrate to Pydantic V2 style `@model_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
[2025-03-09T10:58:35.181+0000] {subprocess.py:93} INFO -   @root_validator(skip_on_failure=True)
[2025-03-09T10:58:35.181+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.8/site-packages/pydantic/_internal/_config.py:267: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
[2025-03-09T10:58:35.182+0000] {subprocess.py:93} INFO -   warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
[2025-03-09T10:58:35.182+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:35,177 : INFO : Starting model training
[2025-03-09T10:58:35.198+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:35,198 : INFO : Registry cache expired, so refreshing
[2025-03-09T10:58:35.207+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:35,207 : INFO : Getting data
[2025-03-09T10:58:35.208+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:35,208 : INFO : Start and End Range: 1 to 1000
[2025-03-09T10:58:35.880+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:35,880 : INFO : Data fetched: 999
[2025-03-09T10:58:35.881+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:35,880 : INFO : New Start and End Range: 1001 to 2000
[2025-03-09T10:58:35.882+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:35,881 : INFO : Start and End Range: 1001 to 2000
[2025-03-09T10:58:36.332+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:36,332 : INFO : Data fetched: 999
[2025-03-09T10:58:36.333+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:36,332 : INFO : New Start and End Range: 3001 to 4000
[2025-03-09T10:58:36.333+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:36,333 : INFO : Start and End Range: 3001 to 4000
[2025-03-09T10:58:37.025+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:37,024 : INFO : Data fetched: 999
[2025-03-09T10:58:37.025+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:37,024 : INFO : New Start and End Range: 7001 to 8000
[2025-03-09T10:58:37.025+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:37,025 : INFO : Start and End Range: 7001 to 8000
[2025-03-09T10:58:37.669+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:37,668 : INFO : Data fetched: 999
[2025-03-09T10:58:37.669+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:37,669 : INFO : New Start and End Range: 15001 to 16000
[2025-03-09T10:58:37.670+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:37,669 : INFO : Start and End Range: 15001 to 16000
[2025-03-09T10:58:38.511+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:38,510 : INFO : Data fetched: 999
[2025-03-09T10:58:38.511+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:38,511 : INFO : New Start and End Range: 31001 to 32000
[2025-03-09T10:58:38.511+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:38,511 : INFO : Start and End Range: 31001 to 32000
[2025-03-09T10:58:39.204+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:39,203 : INFO : Data fetched: 999
[2025-03-09T10:58:39.204+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:39,203 : INFO : New Start and End Range: 63001 to 64000
[2025-03-09T10:58:39.204+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:39,204 : INFO : Start and End Range: 63001 to 64000
[2025-03-09T10:58:39.322+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:39,322 : INFO : Reached End of Data
[2025-03-09T10:58:39.328+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:39,327 : INFO : Stoping at Start and End Range: 63001 to 64000
[2025-03-09T10:58:39.328+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:39,327 : INFO : Created feature data
[2025-03-09T10:58:39.328+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:39,328 : INFO : Total Data fetched: 6
[2025-03-09T10:58:39.340+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:39,339 : INFO : received feature data
[2025-03-09T10:58:39.349+0000] {subprocess.py:93} INFO - 2025-03-09 10:58:39,349 : INFO : Models defined
[2025-03-09T10:58:39.349+0000] {subprocess.py:93} INFO - Error in model training: __init__() got an unexpected keyword argument 'probability'
[2025-03-09T10:58:39.921+0000] {subprocess.py:93} INFO - On branch main
[2025-03-09T10:58:39.921+0000] {subprocess.py:93} INFO - Your branch is up to date with 'origin/main'.
[2025-03-09T10:58:39.921+0000] {subprocess.py:93} INFO - 
[2025-03-09T10:58:39.922+0000] {subprocess.py:93} INFO - Changes to be committed:
[2025-03-09T10:58:39.922+0000] {subprocess.py:93} INFO -   (use "git restore --staged <file>..." to unstage)
[2025-03-09T10:58:39.922+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=scheduled__2025-03-08T08:00:00+00:00/task_id=feature_store_task/attempt=1.log
[2025-03-09T10:58:39.922+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=scheduled__2025-03-08T08:00:00+00:00/task_id=model_training_task/attempt=1.log
[2025-03-09T10:58:39.923+0000] {subprocess.py:93} INFO - 	modified:   logs/model_training.log
[2025-03-09T10:58:39.923+0000] {subprocess.py:93} INFO - 
[2025-03-09T10:58:39.923+0000] {subprocess.py:93} INFO - Untracked files:
[2025-03-09T10:58:39.923+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to include in what will be committed)
[2025-03-09T10:58:39.923+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/online_store.db
[2025-03-09T10:58:39.924+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/registry.db
[2025-03-09T10:58:39.924+0000] {subprocess.py:93} INFO - 	models/
[2025-03-09T10:58:39.924+0000] {subprocess.py:93} INFO - 	online.db
[2025-03-09T10:58:39.924+0000] {subprocess.py:93} INFO - 
[2025-03-09T10:58:39.955+0000] {subprocess.py:93} INFO - [main a670886] Trained model version
[2025-03-09T10:58:39.955+0000] {subprocess.py:93} INFO -  3 files changed, 173 insertions(+)
[2025-03-09T10:58:39.955+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=scheduled__2025-03-08T08:00:00+00:00/task_id=feature_store_task/attempt=1.log
[2025-03-09T10:58:39.956+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=scheduled__2025-03-08T08:00:00+00:00/task_id=model_training_task/attempt=1.log
[2025-03-09T10:58:39.956+0000] {subprocess.py:93} INFO - /bin/bash: line 3:  : command not found
[2025-03-09T10:58:41.440+0000] {subprocess.py:93} INFO - To https://github.com/anniemathew-trial/customer_churn_pipeline.git
[2025-03-09T10:58:41.441+0000] {subprocess.py:93} INFO -    7775711..a670886  main -> main
[2025-03-09T10:58:41.447+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-09T10:58:41.503+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=customer_churn_ml_pipeline, task_id=model_training_task, execution_date=20250308T080000, start_date=20250309T105828, end_date=20250309T105841
[2025-03-09T10:58:41.532+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-09T10:58:41.571+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
