[2025-03-02T10:28:23.754+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_storage_task manual__2025-03-02T10:27:04.760543+00:00 [queued]>
[2025-03-02T10:28:23.769+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_storage_task manual__2025-03-02T10:27:04.760543+00:00 [queued]>
[2025-03-02T10:28:23.770+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-02T10:28:23.795+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_storage_task> on 2025-03-02 10:27:04.760543+00:00
[2025-03-02T10:28:23.801+0000] {standard_task_runner.py:57} INFO - Started process 11534 to run task
[2025-03-02T10:28:23.806+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_storage_task', 'manual__2025-03-02T10:27:04.760543+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmpzx8cueph']
[2025-03-02T10:28:23.810+0000] {standard_task_runner.py:85} INFO - Job 161: Subtask data_storage_task
[2025-03-02T10:28:23.838+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-02T10:28:23.904+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_storage_task manual__2025-03-02T10:27:04.760543+00:00 [running]> on host 9113a5746a05
[2025-03-02T10:28:24.053+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_storage_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T10:27:04.760543+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T10:27:04.760543+00:00'
[2025-03-02T10:28:24.054+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-02T10:28:24.055+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t\t\tcd /opt/***\n                        dvc pull /opt/***/data/transformed\n                        python /opt/***/executables/data_storage.py && \t\t\tgit add logs &&    \t\t\tgit status &&                         git commit -m "Updated stored data version" -a &&                         dvc push && git push\n                    ']
[2025-03-02T10:28:24.069+0000] {subprocess.py:86} INFO - Output:
[2025-03-02T10:28:28.908+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-02T10:28:31.223+0000] {subprocess.py:93} INFO - 2025-03-02 10:28:31,223 : INFO : Connecting to Database
[2025-03-02T10:28:31.225+0000] {subprocess.py:93} INFO - 2025-03-02 10:28:31,225 : ERROR : Error storing data: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '{ODBC Driver 17 for SQL Server};SERVER=dmml_customer_churn_setup-sqlserver-1,1433;DATABASE=customer_churn_db;UID=sa;PWD=NewPASS1234' : file not found (0) (SQLDriverConnect)")
[2025-03-02T10:28:31.432+0000] {subprocess.py:93} INFO - On branch main
[2025-03-02T10:28:31.432+0000] {subprocess.py:93} INFO - Your branch is up to date with 'origin/main'.
[2025-03-02T10:28:31.433+0000] {subprocess.py:93} INFO - 
[2025-03-02T10:28:31.433+0000] {subprocess.py:93} INFO - Changes to be committed:
[2025-03-02T10:28:31.433+0000] {subprocess.py:93} INFO -   (use "git restore --staged <file>..." to unstage)
[2025-03-02T10:28:31.433+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-02T10:27:04.760543+00:00/task_id=data_storage_task/attempt=1.log
[2025-03-02T10:28:31.434+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-02T10:27:04.760543+00:00/task_id=data_transformation_task/attempt=1.log
[2025-03-02T10:28:31.434+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_processor_manager/dag_processor_manager.log
[2025-03-02T10:28:31.434+0000] {subprocess.py:93} INFO - 	modified:   logs/data_storage.log
[2025-03-02T10:28:31.434+0000] {subprocess.py:93} INFO - 
[2025-03-02T10:28:31.434+0000] {subprocess.py:93} INFO - Untracked files:
[2025-03-02T10:28:31.435+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to include in what will be committed)
[2025-03-02T10:28:31.435+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/
[2025-03-02T10:28:31.435+0000] {subprocess.py:93} INFO - 
[2025-03-02T10:28:31.502+0000] {subprocess.py:93} INFO - [main 5e11d0d] Updated stored data version
[2025-03-02T10:28:31.503+0000] {subprocess.py:93} INFO -  4 files changed, 52 insertions(+)
[2025-03-02T10:28:31.503+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-02T10:27:04.760543+00:00/task_id=data_storage_task/attempt=1.log
[2025-03-02T10:28:36.986+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-02T10:28:38.820+0000] {subprocess.py:93} INFO - To https://github.com/anniemathew-trial/customer_churn_pipeline.git
[2025-03-02T10:28:38.821+0000] {subprocess.py:93} INFO -    e429426..5e11d0d  main -> main
[2025-03-02T10:28:38.827+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-02T10:28:38.878+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=customer_churn_ml_pipeline, task_id=data_storage_task, execution_date=20250302T102704, start_date=20250302T102823, end_date=20250302T102838
[2025-03-02T10:28:38.911+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-02T10:28:38.954+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
