[2025-03-03T12:44:21.152+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_preparation_task manual__2025-03-03T12:43:37.097392+00:00 [queued]>
[2025-03-03T12:44:21.164+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_preparation_task manual__2025-03-03T12:43:37.097392+00:00 [queued]>
[2025-03-03T12:44:21.165+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-03T12:44:21.187+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_preparation_task> on 2025-03-03 12:43:37.097392+00:00
[2025-03-03T12:44:21.192+0000] {standard_task_runner.py:57} INFO - Started process 981 to run task
[2025-03-03T12:44:21.196+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_preparation_task', 'manual__2025-03-03T12:43:37.097392+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmp_apzsqix']
[2025-03-03T12:44:21.199+0000] {standard_task_runner.py:85} INFO - Job 79: Subtask data_preparation_task
[2025-03-03T12:44:21.228+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T12:44:21.279+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_preparation_task manual__2025-03-03T12:43:37.097392+00:00 [running]> on host 157237bff8f7
[2025-03-03T12:44:21.387+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_preparation_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T12:43:37.097392+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T12:43:37.097392+00:00'
[2025-03-03T12:44:21.388+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-03T12:44:21.389+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t\t\tcd /opt/*** &&\t\t\tpython /opt/***/executables/data_preparation.py &&                         dvc add /opt/***/data/cleaned &&                         git add /opt/***/data/cleaned.dvc && \t\t\tgit add logs && \\   \n\t\t\tgit add visualization &&    \t\t\tgit status &&                         git commit -m "Updated cleaned data version" -a &&                         dvc push && git push\n                    ']
[2025-03-03T12:44:21.399+0000] {subprocess.py:86} INFO - Output:
[2025-03-03T12:44:24.193+0000] {subprocess.py:93} INFO - 2025-03-03 12:44:24,192 : INFO : Starting data preparation for customer_data.csv.
[2025-03-03T12:44:24.214+0000] {subprocess.py:93} INFO - 2025-03-03 12:44:24,214 : INFO : Dropping 'Tenure' less than 0 and greater than 110 * 12
[2025-03-03T12:44:24.215+0000] {subprocess.py:93} INFO - 2025-03-03 12:44:24,214 : ERROR : Error in preparing data'tenure'
[2025-03-03T12:44:24.215+0000] {subprocess.py:93} INFO - 2025-03-03 12:44:24,215 : INFO : Starting data preparation for database_data.csv.
[2025-03-03T12:44:24.235+0000] {subprocess.py:93} INFO - 2025-03-03 12:44:24,234 : INFO : Dropping 'Tenure' less than 0 and greater than 110 * 12
[2025-03-03T12:44:24.235+0000] {subprocess.py:93} INFO - 2025-03-03 12:44:24,235 : ERROR : Error in preparing data'tenure'
[2025-03-03T12:44:26.596+0000] {subprocess.py:93} INFO - 
[2025-03-03T12:44:26.597+0000] {subprocess.py:93} INFO - To track the changes with git, run:
[2025-03-03T12:44:26.597+0000] {subprocess.py:93} INFO - 
[2025-03-03T12:44:26.597+0000] {subprocess.py:93} INFO - 	git add data/cleaned.dvc
[2025-03-03T12:44:26.597+0000] {subprocess.py:93} INFO - 
[2025-03-03T12:44:26.597+0000] {subprocess.py:93} INFO - To enable auto staging, run:
[2025-03-03T12:44:26.598+0000] {subprocess.py:93} INFO - 
[2025-03-03T12:44:26.598+0000] {subprocess.py:93} INFO - 	dvc config core.autostage true
[2025-03-03T12:44:26.866+0000] {subprocess.py:93} INFO - /bin/bash: line 2:  : command not found
[2025-03-03T12:44:26.893+0000] {subprocess.py:93} INFO - On branch main
[2025-03-03T12:44:26.893+0000] {subprocess.py:93} INFO - Your branch is up to date with 'origin/main'.
[2025-03-03T12:44:26.894+0000] {subprocess.py:93} INFO - 
[2025-03-03T12:44:26.894+0000] {subprocess.py:93} INFO - Changes to be committed:
[2025-03-03T12:44:26.894+0000] {subprocess.py:93} INFO -   (use "git restore --staged <file>..." to unstage)
[2025-03-03T12:44:26.894+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T12:43:37.097392+00:00/task_id=data_preparation_task/attempt=1.log
[2025-03-03T12:44:26.895+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T12:43:37.097392+00:00/task_id=data_validation_task/attempt=1.log
[2025-03-03T12:44:26.895+0000] {subprocess.py:93} INFO - 	modified:   logs/data_preparation.log
[2025-03-03T12:44:26.895+0000] {subprocess.py:93} INFO - 
[2025-03-03T12:44:26.895+0000] {subprocess.py:93} INFO - Changes not staged for commit:
[2025-03-03T12:44:26.895+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to update what will be committed)
[2025-03-03T12:44:26.896+0000] {subprocess.py:93} INFO -   (use "git restore <file>..." to discard changes in working directory)
[2025-03-03T12:44:26.896+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T12:43:37.097392+00:00/task_id=data_preparation_task/attempt=1.log
[2025-03-03T12:44:26.896+0000] {subprocess.py:93} INFO - 
[2025-03-03T12:44:26.896+0000] {subprocess.py:93} INFO - Untracked files:
[2025-03-03T12:44:26.896+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to include in what will be committed)
[2025-03-03T12:44:26.897+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/online_store.db
[2025-03-03T12:44:26.897+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/registry.db
[2025-03-03T12:44:26.897+0000] {subprocess.py:93} INFO - 	models/
[2025-03-03T12:44:26.897+0000] {subprocess.py:93} INFO - 	online.db
[2025-03-03T12:44:26.898+0000] {subprocess.py:93} INFO - 
[2025-03-03T12:44:26.919+0000] {subprocess.py:93} INFO - [main ba1758f] Updated cleaned data version
[2025-03-03T12:44:26.919+0000] {subprocess.py:93} INFO -  3 files changed, 101 insertions(+)
[2025-03-03T12:44:26.919+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T12:43:37.097392+00:00/task_id=data_preparation_task/attempt=1.log
[2025-03-03T12:44:26.920+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T12:43:37.097392+00:00/task_id=data_validation_task/attempt=1.log
[2025-03-03T12:44:32.237+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-03T12:44:33.920+0000] {subprocess.py:93} INFO - To https://github.com/anniemathew-trial/customer_churn_pipeline.git
[2025-03-03T12:44:33.920+0000] {subprocess.py:93} INFO -    2281e21..ba1758f  main -> main
[2025-03-03T12:44:33.925+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-03T12:44:33.967+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=customer_churn_ml_pipeline, task_id=data_preparation_task, execution_date=20250303T124337, start_date=20250303T124421, end_date=20250303T124433
[2025-03-03T12:44:34.026+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-03T12:44:34.062+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
